### ISSUE TITLE
Missing AllowPlainTextPkce on Client Entity

### ISSUE THREAD

**Issue by DerAlbertCom** [IdentityServer/IdentityServer4.EntityFramework#27]
The Client Entity is missing the AllowPlainTextPkce property, which is present on the Client Model of IdServer4

**Comment by scottbrady91** [comment]
Well spotted again. Will look into releasing this as an update.

**Comment by DerAlbertCom** [comment]
You can write a Unit Test for testing the AutoMapper Mappings, with that these would be found in no time. I had to write little Administration Interface the find these ;)

**Comment by scottbrady91** [comment]
There are currently unit tests for the mapper configuration, however the Automapper configuration only cares that all of the Client model's properties are mapped. The EF entities can then be extended but IdentityServer, by default, doesn't need to care about these changes unless explicitly made to.

I also just realized that `AllowPlainTextPkce` is only available on the dev branch and has not yet been released, that's why it's not being mapped.

**Comment by DerAlbertCom** [comment]
Mapper.AssertConfigurationIsValid() is your friend with that. this will ensure that everything is mapped, or ignore if no mapping is needed.

**Comment by scottbrady91** [comment]
Way ahead of you: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/test/IdentityServer4.EntityFramework.UnitTests/Mappers/ClientMappersTests.cs#L24

But as I said we're only checking for model data loss, not the EF entities, which is why the two old properties made it through before.
