### ISSUE TITLE
Provide extra implementations of dbcontexts

### ISSUE THREAD

**Issue by xrkolovos** [IdentityServer/IdentityServer4.EntityFramework#70]
We would like a soulution for our app that has one unified dbcontext. This dbcontext we would like to inherit from IdentityDbContext. It would be nice to work like it. Just inherit and everything works (IdSrv && asp.net Identity).  I thing it should be in a seperated package.
We did it ourselves, but i think it would be nice to have it implemented.

**Comment by brockallen** [comment]
You can do your own single DbContext as long as they implement these interfaces: https://github.com/IdentityServer/IdentityServer4.EntityFramework/tree/dev/src/IdentityServer4.EntityFramework/Interfaces

**Comment by mpetito** [comment]
@brockallen I'm finding that may not be true.  There is a dependency on the `PersistedGrantDbContext` in TokenCleanup here:

https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/2f6065a652cce2d8d6112c70d237a7dae8ece4fd/src/IdentityServer4.EntityFramework/TokenCleanup.cs#L93

It seems like this should be `IPersistedGrantDbContext`?  Otherwise, token cleanup will not work when using your own context.

Furthermore, there's no easy way to register your own context without undoing some of the built in service registration performed by `IdentityServerEntityFrameworkBuilderExtensions` because `TryAdd` isn't used. 
 For example, I need to call `AddOperationalStore` but then replace registrations for `IPersistedGrantDbContext`.

**Comment by scottbrady91** [comment]
Okay, that does sound like it should be `IPersistedGrantDbContext`. Same with the `TryAdd`.

But either way, why are you extending the `PersistedGrantDbContext`?

**Comment by mpetito** [comment]
> We would like a soulution for our app that has one unified dbcontext.

I have a similar design requirement, and wish to implement `IPersistedGrantDbContext` on a `DbContext` which already inherits from `IdentityDbContext`.

**Comment by scottbrady91** [comment]
Sure, I get that. But why is it a requirement? I have nothing against it, just trying to understand the use case and whether or not it's something that needs address/documenting better.

Is there a reason you would need to manage Identity data at the same time as IdentityServer data?

**Comment by mpetito** [comment]
This is more for ease of configuration in my case and access to `OnModelCreating`, so that the same model conventions are applied to the IdentityServer tables.

**Comment by brockallen** [comment]
Ok, yes good point on token cleanup (and sorry it's taken me this long to get to it). I have changed it for 2.0.

**Comment by brockallen** [comment]
@xrkolovos and the original intent with the design was to allow people to use one type of store without the others.
