### ISSUE TITLE
PersistedGrantDbContext sample

### ISSUE THREAD

**Issue by raigol** [IdentityServer/IdentityServer4.EntityFramework#73]
I am following the Quickstart 8 Entity Framework tutorial. 
but when adding migrations

dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb

I get 
No DbContext named 'PersistedGrantDbContext' was found. 

I tried to create PersistedGrantDbContext, but then ran into other issues.

Do you have a good sample PersistedGrantDbContext?

**Comment by dhswg20077** [comment]
how did you fix this ? I have the same issue

**Comment by moritzgloeckl** [comment]
@dhswg20077 Okay I had the same issue and I solved it. It happens when there's an exception in your `Startup.cs > ConfigureServices`. Wrap the whole code like this:

```
public void ConfigureServices(IServiceCollection services)
{
      try {
           //all the code here
      } catch(Exception e) {
           Console.WriteLine(ex.ToString());
           throw;
      }
}
```
So you can exactly find out what's wrong. In my case it was a `FileNotFoundException` so I just commented the lines and it works now.

**Comment by CamiloTerevinto** [comment]
@dhswg20077 As @moritzgloeckl, a try-catch block in my case also helped solve the issue, since an exception was being thrown and not output to the console
