### ISSUE TITLE
use this package with postgres?

### ISSUE THREAD

**Issue by mshanak** [IdentityServer/IdentityServer4.EntityFramework#78]
hello
can i use this package with postgres entity framework ?

**Comment by brockallen** [comment]
Yes, it has been used successfully with postgres.

**Comment by baez90** [comment]
I had a minor problem when I was generating the migrations as explained in the docs because there was a annotation missing for the *ValueGenerationStrategy* when MSSQL **and** Postgres are both targeted.

If you encounter a problem when you try to create new claims, identity resources or anything else, have a look at this snippet copied from my migrations:

```cs
 Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
```

by adding the *npgsql*-specific ValueGenerationStrategy my problems were sovled

**Comment by brockallen** [comment]
Good tip, thanks for the info.
