### ISSUE TITLE
Unable to open Wiki page

### ISSUE THREAD

**Issue by MNF** [IdentityServer/IdentityServer4.EntityFramework#94]
When I am trying to click Wiki page(https://github.com/IdentityServer/IdentityServer4.EntityFramework/wiki), it opens home https://github.com/IdentityServer/IdentityServer4.EntityFramework page instead.
Please allow users to contribute to your documentation

**Comment by leastprivilege** [comment]
Our documentation is here:

https://identityserver4.readthedocs.io/en/release/

If you want to contribute - please start an issue on our main repo
https://github.com/IdentityServer/IdentityServer4

**Comment by michael-freidgeim-webjet** [comment]
@leastprivilege Dominick, community supported wiki provided different ways to describe the features, than official documentation. Raising issues for some minor changes/additions in documentations is a relatively long process, that required more time spend by requestors and owners. Having wiki is the easiest process for contributors and doesn't required any effort for owners. At the same time you (and anyone else) always able to change/delete any incorrect information. 
Also you have wiki enabled on https://github.com/IdentityServer/IdentityServer4/wiki and https://github.com/IdentityServer/IdentityServer4.Samples/wiki (actually started by me). 
Why it doesn't work for https://github.com/IdentityServer/IdentityServer4.EntityFramework/wiki ?

Actually I just wanted in this repository to provide link to particular https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html and also 
  which Entity Framework Core  implementations are supported (https://docs.microsoft.com/en-us/ef/core/providers/).

**Comment by leastprivilege** [comment]
I don't even knew you added content to the samples wiki - and there's the problem.

We have like 30+ repos and it is very hard to track them all. How do I know that what you (or someone else) are adding to those 30+ wikis is correct without a formal review process?

I'd like to have **one** place for docs.

**Comment by michael-freidgeim-webjet** [comment]
Wiki is supposed to be maintained by community, not by authors of the project, it doesn't expect formal review process. Wikipedia and StackOverflow rely on the community to maintain content and fix what is wrong. It is not an official documentation and you don't need to spend your valuable time to review content.

You have a good documentation, but some information can be presented from the different angle, that may be not suatable for an official documentation.  Wiki is very easy to contribute, submit pull request for documentation  is more annoying process, and many people will not do it. Wiki can give your users more useful  information without any effort from yourself.

> I'd like to have **one** place for docs.

You do have one place for official docs. Put at the wiki home page link to **relevant** official documentation (e.g. https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html for this repository) and note that wiki pages are not endorced by owners of the project and maintained by community.
If you later will find some wiki page suatable for official documentation, you can move it.

Related point: at the moment a lot of information spread on different answers in GitHub and SO, but find them (in particular in GitHub issues) not easy. Moving them to one place (official docs or wiki) will be useful.

I thought that it's just some misconfigured setting in this repository. But if it is your intentional decision to disable wiki, I will submit my changes as pull request for readme.md.
